export {default as Home} from './Home';
export {default as Products} from './Products';
export {default as CategoryProducts} from './Category.Products';
export {default as ProductDetails} from './ProductDetails';
export {default as SearchProducts} from './Search.Products';
export {default as Shop} from './Shop';
export {default as Checkout} from './Checkout';
export {default as ConfirmOrder} from './Confirm.Order';
export {default as WishList} from './WishList';
export {default as UserDashboard} from './client/UserDashboard';
export {default as UserContact} from './client/User.Contact';
export {default as UserProfile} from './client/User.Profile';
export {default as UserUpdateProfile} from './client/User.Update.Profile';
export {default as UserOrders} from './client/User.Orders';
export {default as UserConfirmOrder} from './client/User.Confirm.Order';
export {default as VendorDashboard} from './vendor/VendorDashboard';
export {default as VendorProfile} from './vendor/Vendor.Profile';
export {default as VendorOrders} from './vendor/Vendor.Orders';
export {default as VendorProducts} from './vendor/Vendor.Products';
export {default as VendorAddProduct} from './vendor/Vendor.Add.Product';
export {default as VendorEditProduct} from './vendor/Vendor.Edit.Product';
export {default as VendorHistory} from './vendor/Vendor.History';
export {default as VendorUpdate} from './vendor/VendorUpdate'
export {default as VendorContact} from './vendor/Vendor.Contact';
export {default as VendorProductDeatils} from './vendor/Vendor.Deatils.Product';
export {default as AdminDashboard} from './admin/AdminDashboard';
export {default as Signup} from './Signup';
export {default as Login} from './Login';
export {default as CheckboxType} from './CheckboxType';
export {default as ResetPassword} from './ResetPassword';

export {default as AdminProfile} from './admin/Admin.Profile';
export {default as Clients} from './admin/Admin.CLients';
export {default as AcceptedVendors} from './admin/Admin.AcceptedVendors'; 
export {default as PendingVendors} from './admin/Admin.PendingVednors';
export {default as AdminUpdate} from './admin/Admin.Upadte';
export {default as ClientMessages} from './admin/Admin.ClientsMessages';
export {default as VendorMessages} from './admin/Admin.VendorsMessages';
 
