export {default as Home} from './Home';
export {default as Products} from './Products';
export {default as ProductDetails} from './ProductDetails';
export {default as Shop} from './Shop';
export {default as Checkout} from './Checkout';
export {default as WishList} from './WishList';
export {default as UserDashboard} from './UserDashboard';
export {default as VendorDashboard} from './VendorDashboard';
export {default as VendorProfile} from './Vendor.Profile';
export {default as VendorOrders} from './Vendor.Orders';
export {default as VendorProducts} from './Vendor.Products';
export {default as VendorAddProduct} from './Vendor.Add.Product';
export {default as VendorEditProduct} from './Vendor.Edit.Product';
export {default as VendorHistory} from './Vendor.History';
export {default as AdminDashboard} from './AdminDashboard';
export {default as Signup} from './Signup';
export {default as Login} from './Login';
export {default as CheckboxType} from './CheckboxType';
export {default as Contact} from './Contact';
export {default as ResetPassword} from './ResetPassword';
export {default as VendorUpdate} from './VendorUpdate'

